In [1]:
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils import data

import numpy as np
import pandas as pd

from rocket import Rocket

import random

In [3]:
model=torch.load('model.pt')

In [4]:
model

OrderedDict([('fc1.weight',
              tensor([[-1.9795e-01, -4.4692e-01, -3.1836e-01,  3.6091e-01,  1.0350e-02],
                      [-3.7264e-01, -9.8958e-01, -2.7671e-01, -7.2311e-01,  2.1425e-02],
                      [-4.1122e-02, -4.3205e-01,  7.1248e-02,  5.3607e-01, -7.6547e-03],
                      [-3.4746e-02,  3.4034e-01, -1.5078e-01, -2.9734e-01, -3.8266e-02],
                      [ 2.3715e-01, -3.2636e-01,  3.2486e-01,  3.8179e-01,  1.1720e-02],
                      [ 1.1340e-04,  3.2583e-01, -2.0588e-02, -3.8398e-01,  3.4968e-01],
                      [-1.1004e-01, -4.7477e-01,  1.3646e-01,  6.3746e-01, -6.2841e-02],
                      [-2.0391e-01, -3.1122e-01, -1.4083e-01,  4.3718e-01, -5.8921e-01],
                      [ 8.1575e-01,  4.6442e-01,  2.4631e-01, -3.5536e-01, -5.6952e-02],
                      [ 1.7442e-01, -6.6269e-01,  2.7840e-01,  2.7295e-01, -8.0584e-02],
                      [ 2.3440e-01,  1.3537e-01,  1.9044e-01,  3.3325e-01, -1.0465

In [15]:
x = torch.tensor([0,1500., 0, -20, 7000])

In [16]:
x

tensor([   0., 1500.,    0.,  -20., 7000.])

In [8]:
model.eval()

AttributeError: 'collections.OrderedDict' object has no attribute 'eval'

In [9]:
class Net(nn.Module):
    
    def __init__(self):
        super(Net, self).__init__()
        
        d = 16
        self.fc1 = nn.Linear(5, d)
        self.fc2 = nn.Linear(d, d)
        self.fc3 = nn.Linear(d, 2)
        
        a = (12/(5+d))**0.5
        nn.init.uniform_(self.fc1.weight, a=-a, b=a)
        
        a = (12/(d+d))**0.5
        nn.init.uniform_(self.fc2.weight, a=-a, b=a)
        
        a = (6/(d+2))**0.5
        nn.init.uniform_(self.fc3.weight, a=-a, b=a)
        
    def forward(self, x):
        
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = torch.tanh(self.fc3(x))
        
        return x
    
    

In [10]:
net = Net()

In [11]:
net.load_state_dict(model)

<All keys matched successfully>

In [12]:
net.eval()

Net(
  (fc1): Linear(in_features=5, out_features=16, bias=True)
  (fc2): Linear(in_features=16, out_features=16, bias=True)
  (fc3): Linear(in_features=16, out_features=2, bias=True)
)

In [17]:
net(x)

tensor([1.0000, 1.0000], grad_fn=<TanhBackward>)